##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Coveralls example:
#    https://github.com/marketplace/actions/coveralls-github-action
#
##############################################################################

name: Build

on:
  # Triggered whenever push to the main branch
  push:
    branches: [ "master" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "master" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04
    
    steps:
      # We want to use GitHub CI checkout version 3 to check out our branches
      - name: Checking out
        uses: actions/checkout@v3

      - name: Git install and colcon extensions
        run : |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) \
            signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
            http://packages.ros.org/ros2/ubuntu \
            $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
            | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
          sudo apt install -y lcov
          
      - name: Configure CMake flags and build exectables
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --cmake-args -DCOVERAGE=1 --packages-select Delivery_Bot
          cat log/latest_build/Delivery_Bot/stdout_stderr.log
          find build/Delivery_Bot/ | grep -E 'gcno' # catch error -- exepct to see .gcno files
          
      # Install Gazebo ROS and other dependencies
      - name: CMake Dependencies for the package
        run: |
          sudo apt install ros-humble-gazebo-ros-pkgs
      
      - name: Run unit test and check code error
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select Delivery_Bot
          cat log/latest_test/Delivery_Bot/stdout_stderr.log
          find build/Delivery_Bot/ | grep -E 'gcda' # catch error -- expect to see .gcda files
          colcon test-result --test-result-base build/Delivery_Bot/ # catch error
      
      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ${{github.workspace}}/install/delivery_bot/lib/delivery_bot/coverage_cleaned.info
          # flags: unittests # optional
          # directory: ${{github.workspace}}/install/
          # name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
